version: '3'
services:
  mysql-pco:
    image: "mysql:8.0.22"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./data-pco-mysql/var_lib_mysql:/var/lib/mysql
